//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int ACC_ID { get; set; }
        public Nullable<int> PRI_ID { get; set; }
        public Nullable<int> EM_ID { get; set; }
        public string ACC_USERNAME { get; set; }
        public string ACC_PASSWORD { get; set; }
        public Nullable<bool> ACC_STATUS { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRIVILE PRIVILE { get; set; }
    }
}
