//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IO_INFO
    {
        public long IO_ID { get; set; }
        public Nullable<System.DateTime> IO_TIME { get; set; }
        public Nullable<int> CONTROLLER_ID { get; set; }
        public Nullable<int> CA_ID { get; set; }
        public Nullable<long> BAR_ID { get; set; }
        public Nullable<int> TFA_ID { get; set; }
    
        public virtual BARCODE BARCODE { get; set; }
        public virtual CARD_NO CARD_NO { get; set; }
        public virtual CONTROLLER CONTROLLER { get; set; }
        public virtual TIME_FRAME_ACTIVE TIME_FRAME_ACTIVE { get; set; }
    }
}
